/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_conan_ndk_image_ImageUtil */

#ifndef _Included_com_conan_ndk_image_ImageUtil
#define _Included_com_conan_ndk_image_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_conan_ndk_image_ImageUtil
 * Method:    convertBitmap
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_conan_ndk_image_ImageUtil_convertBitmap
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
